card/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.base, name='base'),
    path('record', views.record, name='record'),
    path('add/', views.add_order, name='add_order'),
]

settingsSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card.urls'))
]

card/models.py
from django.db import models
from django import forms
from django.conf import settings

# Create your models here.
class Author(models.Model):
    author_title = models.CharField(max_length=256, default='Иван Иванов')
    phone = models.CharField(max_length=20, default='79999999999')
    validate_number = models.BooleanField(default=False)
    description = models.TextField(max_length=5000, null=True)
    stage = models.IntegerField(null=True)
    age = models.IntegerField(null=True)
    profession = models.CharField(max_length=300, null=True)
    amount_reception = models.IntegerField(default=0, null=True)

    def validate_phone_number(self):
        import phonenumbers
        try:
            parsed_number = phonenumbers.parse(self.phone, None)
            if phonenumbers.is_valid_number(parsed_number):
                self.validate_number = True
            else:
                self.validate_number = False
        except phonenumbers.phonenumberutil.NumberParseException:
            self.validate_number = False
    

    def save(self, *args, **kwargs):
        self.validate_phone_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return 'Данные на сайте'

class Order(models.Model):
    phone = models.CharField(max_length=20, default='79999999999', null=True)
    email = models.CharField(max_length=30, null=True)
    description = models.CharField(max_length=400, null=True)

    def validate_phone_number(self):
        import phonenumbers
        try:
            parsed_number = phonenumbers.parse(self.phone, None)
            if phonenumbers.is_valid_number(parsed_number):
                self.validate_number = True
            else:
                self.validate_number = False
        except phonenumbers.phonenumberutil.NumberParseException:
            self.validate_number = False

    def email_validate(self): # Допишешь обработку формы
        pass

    def save(self, *args, **kwargs):
        self.validate_phone_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Tel: {self.phone} | email: {self.email}'

card/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['phone', 'email', 'description']

card/views.py
from django.shortcuts import render, redirect
from .models import Order
from .forms import OrderForm

# Create your views here.
def base(request):
    return render(request, 'card/main_list.html', {})

def record(request):
    return render(request, 'card/record.html', {})

def add_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_page')
    else:
        form = OrderForm()
    
    return render(request, 'card/add_order.html',)
    

card/templates/card/add_order.html
{% extends "card/base.html" %}

{% block content %}
<div class="container">
    <h2>Записаться на прием</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_phone">Номер:</label>
            <input type="text" id="id_phone" name="phone" value="{{ form.phone.value }}">
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="text" id="id_email" name="email" value="{{ form.email.value }}">
        </div>
        <div class="form-group">
            <label for="id_description">Описание:</label>
            <textarea id="id_description" name="description">{{ form.description.value }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
</div>
<!-- Подключите скрипты Bootstrap (при необходимости) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}

card/templates/card/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static "css/card.css" %}">
    <style>@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');</style>
    <title>ps</title>
</head>
<body>
    <header>
        <p>alter</p>
    </header>

    {% block content %}
    {% endblock %}

    <div id='futor'>
    </div>
</body>
</html>

card/templates/card/main_list.html
{% extends "card/base.html" %}

{% block content %}
<div id='Specifications1'>
    <img id='foto' src="https://back.alter.ru/media/avatars/7909800b2dafb7ef987cbbcec359c13ce3b21b69.jpeg" alt='фото'\>
    <h1 id='name'>{{author.author_title}}</h1>
    <p>Клинический психолог Семейный психолог <br> Психолог</p>
    <div id='Specifications2'>
        <p id='Specifications2p'>7 лет опыта &nbsp;&nbsp;&nbsp; 56 лет &nbsp;&nbsp;&nbsp;</p>
        <p id='Verified'>Проверено Alter</p>
    </div>
    <div id='NumberSessions'>
        <p>Болee 200 сессий в Alter</p>
    </div>
</div>

<div id='WhenApply'>
    <div id='WhenApplytext'>
        <h3>Когда обращаются</h3>
        <p><li class='lileft'>Травматические события в прошлом</li> <li>Семейные и партнерские отношения</li></p>
        <p><li class='lileft'>Самоопределение, смысл жизни, другие <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;экзистенциальные вопросы</li> <li>Конфликты, ссоры, трудности в общении</li></p>
        <h3>Аудитория</h3>
        <div id='age'>Взрослые</div>
    </div>
</div>

<div id='price'>
    <h3>4000 ₽</h3>
    <h5>Принимает онлайн</h5>
    <div id='ViewTime' class="PriceButton"><a href = "{% url 'add_order' %}">Посмотреть время</a></div>
    <div id='PsychologistQuestion' class="PriceButton">Задать вопрос психологу</div>
</div>
{% endblock %}

card/templates/card/record.html
{% extends "card/base.html" %}

{% block content %}
<div id='Specifications1'>
    <img id='foto' src="https://back.alter.ru/media/avatars/7909800b2dafb7ef987cbbcec359c13ce3b21b69.jpeg" alt='фото'\>
    <h1 id='name'>Александр Лисичный</h1>
    <p>Клинический психолог Семейный психолог <br> Психолог</p>
    <div id='Specifications2'>
        <p id='Specifications2p'>7 лет опыта &nbsp;&nbsp;&nbsp; 56 лет &nbsp;&nbsp;&nbsp;</p>
        <p id='Verified'>Проверено Alter</p>
    </div>
    <div id='NumberSessions'>
        <p>Болee 200 сессий в Alter</p>
    </div>
</div>
{% endblock %}